export default {
    AskForHelp: "Ask for Help",
    CreateAccount: "Create Account",
    CreateAnAccount: "Create an Account",
    Email: "EMAIL",
    English: "English",
    ErrInvalidLogin: "Invalid email and/or password.",
    ForgotPassword: "Forgot Password",
    ForgottenPassword: "Forgotten password",
    Hello: "Hello.",
    Help: "Help",
    Home: "Home",
    Lessons: "Lessons",
    LogIn: "Login",
    LogOut: "Log Out",
    Messages: "Messages",
    Metronome: "Metronome",
    Music: "Music",
    Minutes: "minutes",
    Name: "NAME",
    Password: "PASSWORD",
    PrivacyPolicy: "Privacy Policy",
    PrivacyPolicyText: "Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text",
    Profile: "Profile",
    Recover: "Recover",
    Recovery: "recovery",
    RequireRelogin: "Your access has been expired and require to login in using user name and password again",
    Send: "Send",
    SendMessage: "Send Message",
    SendMessageToMAL: "Send a message to Music As Language",
    Settings: "Settings",
    SignUp: "Sign Up",
    SongList: "Song List",
    Songs: "Songs",
    TagLine: "#MusicAsLanguage",
    TermsAndConditions: "Terms & Conditions",
    TermsAndConditionsText: "Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text",
    Toolbox: "Toolbox",
    TypeMessage: "Type your message here.",
    MessageSent: "Your message has been sent.",
}