export default {
    AccountDetails: "Account Details",
    CreateAccount: "Create Account",
    CreateAnAccount: "Create an Account",
    Email: "EMAIL",
    English: "English",
    ErrInvalidLogin: "Invalid email and/or password.",
    Hello: "Hello.",
    Help: "Help",
    Home: "Home",
    Language: "Language",
    Lessons: "Lessons",
    LogIn: "Login",
    LogOut: "Log Out",
    Messages: "Messages",
    Metronome: "Metronome",
    Music: "Music",
    Minutes: "minutes",
    Name: "NAME",
    NoAccount: "Don't have an account yet?",
    NoNotifications: "Notifications",
    Notifications: "Notifications",
    Password: "PASSWORD",
    PrivacyPolicy: "Privacy Policy",
    PrivacyPolicyText: "Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text Privacy policy text",
    Settings: "Settings",
    SignUp: "Sign Up",
    TagLine: "#MusicAsLanguage",
    TermsAndConditions: "Terms & Conditions",
    TermsAndConditionsText: "Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text Terms and conditions text",
    Toolbox: "Toolbox",
}