export default {
  Activities: "Activities",
  ActivityCompletionMsg: "You did it!",
  AskForHelp: "Ask for Help",
  CreateAccount: "Create Account",
  CreateAnAccount: "Create an Account",
  Email: "EMAIL",
  English: "English",
  ErrInvalidLogin: "Invalid email and/or password.",
  ForgotPassword: "Forgot Password",
  ForgottenPassword: "Forgotten password",
  Hello: "Hello.",
  Help: "Help",
  Home: "Home",
  Lessons: "Lessons",
  LessonCompletionTitle: "Congrats!",
  LessonCompletionMsg: "Lesson Completed",
  LogIn: "Login",
  LogOut: "Log Out",
  Messages: "Messages",
  MessageSent: "Your message has been sent.",
  Metronome: "Metronome",
  Music: "Music",
  Minutes: "min",
  Name: "NAME",
  OK: "OK",
  OneActivity: "1 Activity",
  Password: "PASSWORD",
  PrivacyPolicy: "Privacy Policy",
  Profile: "Profile",
  Recover: "Recover",
  Recovery: "recovery",
  RequireRelogin:
    "Your access has been expired and require to login in using user name and password again",
  Send: "Send",
  SendMessage: "Send Message",
  SendMessageToMAL: "Send a message to MusicAsLanguage",
  Settings: "Settings",
  SignUp: "Sign Up",
  SongList: "Song List",
  Songs: "Songs",
  TagLine: "#MusicAsLanguage",
  TermsAndConditions: "Terms & Conditions",
  Toolbox: "Toolbox",
  TypeMessage: "Type your message here.",
  VideoWasNotLoadedPullToRetry:
    "Sorry, video was not loaded.\nPlease, pull down to try again.",
};
