export default Object.freeze({
  HOME: "Home",
  LESSON_DETAILS: "LessonDetails",
  ACTIVITI_DETAILS: "Activity",  
  NAVIGATION: "Navigation",
  LOGIN: "Login",
  REGISTER: "Register",
  PASSWORDRESET: "ResetPassword",
  MESSAGES: "Messages",
  TOOLBOX: "Toolbox",
  SONG_LIST:"SongList",
  SETTINGS: "Settings",  
  PROFILE: "Profile",
  TERMS_AND_CONDITIONS: "TermsAndConditions",
  PRIVACY_POLICY: "PrivacyPolicy",
  LOCAL_CACHE: "LocalCache",
});
